<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
use App\SmLanguagePhrase;

class CreateSmLanguagePhrasesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('sm_language_phrases', function (Blueprint $table) {
            $table->collation = 'utf8_general_ci';
            $table->charset = 'utf8';
            $table->increments('id');
            $table->string('modules')->nullable();
            $table->string('default_phrases')->nullable();
            $table->string('en')->nullable();
            $table->tinyInteger('active_status')->default('1');
            $table->timestamps(); 
        });


        $translation_strings = [
            [
                'dashboard' => 'Dashboard',
                'welcome' => 'Welcome',
                'student' => 'Student',
                'total' => 'Total',
                'teachers' => 'Teachers',
                'parents' => 'Parents',
                'staffs' => 'Staffs',
                'income_and_expenses_for' => 'Income and Expenses for',
                'total_income' => 'Total Income',
                'total_expenses' => 'Total Expenses',
                'total_profit' => 'Total Profit',
                'total_revenue' => 'Total Revenue',
                'title' => 'Title',
                'message' => 'Message',
                'actions' => 'Actions',
                'calendar' => 'Calendar',
                'view' => 'View',
                'to_do_list' => 'To Do List',
                'add' => 'Add',
                'edit' => 'Edit',
                'no_do_lists_assigned_yet' => 'No Do Lists Assigned Yet',
            ],
            //end Dashboard

            //start Admin Section
            [
                'admin_section' => 'Admin Section',
                'admission_query' => 'Admission Query',
                'select_criteria' => 'Select Criteria',
                'date_from' => 'Date From',
                'date_to' => 'Date To',
                'select_source' => 'Select Source',
                'select_status' => 'Select status',
                'Status' => 'Status',
                'active' => 'Active',
                'inactive' => 'Inactive',
                'search' => 'Search',
                'query_list' => 'Query List',
                'name' => 'Name',
                'phone' => 'Phone',
                'source' => 'Source',
                'email' => 'Email',
                'query_date' => 'Query Date',
                'last_follow_up_date' => 'last follow up date',
                'next_follow_up_date' => 'next follow up date',
                'select' => 'Select',
                'add_query' => 'Add Query',
                'delete' => 'Delete',
                'delete_admission_query' => 'Delete Admission Query',
                'are_you_sure_to_delete' => 'Are you sure to delete this item?',
                'cancel' => 'Cancel',
                'admission_enquiry' => 'Admission Enquiry',
                'address' => 'Address',
                'description' => 'Description',
                'date' => 'Date',
                'assigned' => 'Assigned',
                'reference' => 'Reference',
                'number_of_child' => 'Number of child',
                'save' => 'Save',
                'visitor_book' => 'Visitor Book',
                'visitor' => 'Visitor',
                'purpose' => 'Purpose',
                'id' => 'ID',
                'no_of_person' => 'No. of Person',
                'in_time' => 'In Time',
                'out_time' => 'Out time',
                'browse' => 'browse',
                'update' => 'Update',
                'visitor_list' => 'Visitor List',
                'download' => 'Download',
                'complaint' => 'Complaint',
                'by' => 'By',
                'type' => 'Type',
                'taken' => 'Taken',
                'list' => 'List',
                'postal_receive' => 'Postal Receive',
                'from_title' => 'From Title',
                'no' => 'No.',
                'note' => 'Note',
                'to_title' => 'To Title',
                'postal_dispatch' => 'Postal Dispatch',
                'phone_call_log' => 'Phone Call Log',
                'phone_call' => 'Phone Call',
                'follow_up_date' => 'Follow Up Date',
                'call_duration' => 'Call Duration',
                'incoming' => 'Incoming',
                'outgoing' => 'Outgoing',
                'call' => 'Call',
                'admin_setup' => 'Admin Setup',
                'student_certificate' => 'Student Certificate',
                'certificate' => 'Certificate',
                'header_left_text' => 'Header left text',
                'body' => 'Body',
                'footer_left_text' => 'Footer left text',
                'footer_center_text' => 'Footer Center text',
                'footer_right_text' => 'Footer Right text',
                'student_photo' => 'Student Photo',
                'yes' => 'yes',
                'none' => 'No',
                'background_image' => 'Background Image',
                'generate_certificate' => 'Generate Certificate',
                'select_section' => 'Select section',
                'generate' => 'Generate',
                'admission' => 'Admission',
                'class_Sec' => 'Class (Sec.)',
                'father' => 'Father',
                'date_of_birth' => 'Date Of Birth',
                'gender' => 'Gender',
                'mobile' => 'Mobile',
                'student_id_card' => 'Student ID Card',
                'id_card_title' => 'ID Card Title',
                'number' => 'Number',
                'mother' => 'Mother',
                'blood_group' => 'Blood Group',
                'id_card' => 'ID Card',
                'generate_id_card'=>'Generate ID Card',
                'all' => 'All',
                'relation_with_guardian'=>'Relation with Guardian',
                'admin'=>'Admin',
                'follow_up'=>'Follow up',
                'follow_up_admission_query'=>'Follow Up Admission Query',
                'response'=>'Response',
                'follow_up_list'=>'Follow Up List',
                'query_by'=>'Query By',
                'delete_follow_up_query'=>'Delete Follow up query',
                'certificate_body_len'=>'Max Character lenght 500',
            ],
            //end Admin Section

            //start student information
            [
                'student_information' => 'Student Info',
                'student_admission' => 'Student Admission',
                'student_import'=>'Student Import',
                'import' => 'Import',
                'personal' => 'Personal',
                'info' => 'Info',
                'roll' => 'Roll',
                'first' => 'First',
                'last' => 'Last',
                'religion' => 'Religion',
                'caste' => 'Caste',
                'category' => 'Category',
                'height' => 'Height',
                'Weight' => 'Weight',
                'sibling' => 'Sibling',
                'information' => 'Information',
                'guardian' => 'Guardian',
                '&' => '&',
                'occupation' => 'Occupation',
                'photo' => 'Photo',
                'Other' => 'Others',
                'relation_with_guardian' => 'Relation with Guardian',
                'current' => 'Current',
                'permanent' => 'Permanent',
                'route_list' => 'Route List',
                'driver' => 'Driver',
                'room' => 'Room',
                'national_iD_number' => 'National ID Number ',
                'local_Id_Number' => 'Local Id Number',
                'bank' => 'Bank',
                'previous_school_details' => 'Previous School Details',
                'additional_notes' => 'Additional Notes',
                'parents_and_guardian_info' => 'PARENTS & GUARDIAN INFO',
                'transport_and_dormitory_info' => 'Transport & Dormitory Info',
                'document_info' => 'Document Info',
                'document_01_title' => 'Document 01 Title',
                'document_02_title' => 'Document 02 Title',
                'document_03_title' => 'Document 03 Title',
                'document_04_title' => 'Document 04 Title',
                'student_details' => 'Student Details',
                'search_by_name' => 'Search By Name',
                'search_by_roll_no' => 'Search By Roll No',
                'father_name' => 'Father\'s Name',
                'student_promote' => 'Student Promote',
                'select_current_session' => 'Select Current Session ',
                'select_current_class' => 'Select current Class',
                'select_current_section' => 'Select Current section',
                'promote_student_in_next_session' => 'Promote Student In Next Session',
                'view_academic_performance' => 'View Academic Performance',
                'pass' => 'Pass',
                'fail' => 'Fail',
                'select_promote_session' => 'Select Promote Session',
                'select_promote_class' => 'Select Promote Class',
                'the_session_is_required' => 'The session is required',
                'the_class_is_required' => 'The class is required',
                'the_section_is_required' => 'The section is required',
                'select_promote_section' => 'Select Promote Section',
                'promote' => 'Promote',
                'student_attendance' => 'Student Attendance',
                'select_class' => 'Select Class',
                'attendance' => 'Attendance',
                'attendance_already_submitted_as_holiday' => 'Attendance Already Submitted As Holiday. You Can Edit Record',
                'attendance_already_submitted' => 'Attendance Already Submitted You Can Edit Record',
                'mark_holiday' => 'Mark Holiday',
                'present' => 'Present',
                'late' => 'Late',
                'absent' => 'Absent',
                'half_day' => 'Half Day',
                'add_note_here' => 'Add Note Here',
                'error' => 'Error',
                'student_attendance_report' => 'Student Attendance Report',
                'january' => 'January',
                'february' => 'February',
                'march' => 'March',
                'april' => 'April',
                'may' => 'May',
                'june' => 'June',
                'july' => 'July',
                'august' => 'August',
                'september' => 'September',
                'october' => 'October',
                'november' => 'November',
                'december' => 'December',
                'select_month' => 'Select Month',
                'select_year' => 'Select Year',
                'student_category' => 'Student Category',
                'student_category_list' => 'Student Category List',
                'student_group' => 'Student Group',
                'group' => 'Group',
                'disabled_student' => 'Disabled Students',
                'student_list' => 'Student List',
                'birth_certificate'=>'Birth Certificate',
                'student_edit'=>'Student Edit',
                'in'=>'In',
                'kg'=>'KG',
                'add_parent'=>'Add Parent',
                'update_information'=>'Update information',
                'siblings'=>'Siblings',
                'guardian_name'=>'Guardian\'s Name',
                'guardian_email'=>'Guardian\'s Email',
                'guardian_phone'=>'Guardian\'s Phone',
                'guardian_occupation'=>'Guardian Occupation',
                'guardian_address'=>'Guardian Address',
                'student_address_info'=>'Student Address Info',
                'current_address'=>'Current Address',
                'permanent_address'=>'Permanent Address',
                'vehicle_number'=>'Vehicle Number',
                'driver_name'=>'Driver Name',
                'bank_name'=>'Bank Name',
                'update_student'=>'update student',
                'remove'=>'Remove',
                'are_you'=>'Are you sure to remove siblings?',
                'download_sample_file'=>'Download Sample File',
             ],
            //end student information

            //last update

            //start teacher
            [
                'teacher' => 'Teacher',
                'upload_content' => 'Upload Content',
                'assignment' => 'Assignment',
                'content_title' => 'Content Title',
                'study_material' => 'Study Material',
                'syllabus' => 'Syllabus',
                'other_download' => 'Other Downloads',
                'available_for' => 'Available for',
                'admin' => 'Admin',
                'available_for_all_classes' => 'Available for all classes',
                'action' => 'Action',
                'other_downloads_list' => 'Other Downloads List'
            ],
            //end teacher

            //start Fees Collection
            [
                'fees_collection' => 'Fees Collection',
                'collect_fees' => 'Collect Fees',
                'search_fees_payment' => 'Search Fees Payment',
                'search_fees_due' => 'Search Fees Due',
                'fees_master' => 'Fees Master',
                'fees_group' => 'Fees Group',
                'fees_type' => 'Fees Type',
                'fees_discount' => 'Fees Discount',
                'fees_forward' => 'Fees Carry Forward',
                'payment' => 'Payment',
                'payment_ID_Details' => 'Payment ID Details',
                'mode' => 'Mode',
                'amount' => 'Amount',
                'discount' => 'Discount',
                'fine' => 'Fine',
                'fees_due_list' => 'Fees Due List',
                'due_birth' => 'Due Birth',
                'deposit' => 'Deposit',
                'balance' => 'Balance',
                'master' => 'Master',
                'assign' => 'Assign',
                'item' => 'Item',
                'content' => 'content',
                'fees_code' => 'Fees Code',
                'code' => 'Code',
                'once' => 'Once',
                'year' => 'Year',
                'previous_Session_Balance_Fees' => 'Previous Session Balance Fees',
                'previous_balance_can_only_update_now.' => 'Previous balance already forwarded, you can only update now.'
            ],

            //end Fees Collection

            //Start Account
            [
                'accounts' => 'Accounts',
                'profit' => 'Profit',
                'income' => 'Income',
                'expense' => 'Expense',
                'chart_of_account' => 'Chart Of Account',
                'payment_method' => 'Payment Method',
                'bank_account' => 'Bank Account',
                'a_c_Head' => 'A/C Head',
                'add_expense' => 'Add Expense',
                'search_income_expense' => 'Search Income/Expense',
                'item_Receive' => 'Item Receive',
                'income_Head' => 'Income Head',
                'sells' => 'Sells',
                'grand_total' => 'Grand Total',
                'expense_head' => 'Expense Head',
                'purchase' => 'Purchase',
                'from' => 'From',
                'head' => 'Head',
                'method' => 'Method',
                'account_name' => 'Account Name',
                'opening_balance' => 'Opening Balance ',
                'account' => 'Account'],
            //end Account

            //start human resource
            [
                'human_resource' => 'Human resource',
                'staff_directory' => 'Staff Directory',
                'staff_attendance' => 'Staff Attendance',
                'staff_attendance_report' => 'Staff Attendance Report',
                'payroll' => 'Payroll',
                'payroll_report' => 'Payroll Report',
                'approve_leave_request' => 'Approve Leave Request',
                'apply_leave' => 'Apply Leave',
                'leave_type' => 'Leave type',
                'department' => 'Department',
                'designation' => 'Designation',
                'staff_list' => 'Staff List',
                'add_staff' => 'Add Staff',
                'search_by_staff_id' => 'Search By Staff ID',
                'staff' => 'Staff',
                'select_role' => 'Select Role',
                'generate_payroll' => 'Generate Payroll',
                'generated' => 'Generate',
                'paid' => 'Paid',
                'not' => 'Not',
                'proceed_to_pay' => 'Proceed to Pay',
                'view_payslip' => 'View Payslip',
                'month' => 'Month',
                'payslip' => 'Payslip',
                'basic_salary' => 'Basic Salary',
                'earnings' => 'Earnings',
                'deductions' => 'Deductions',
                'gross_salary' => 'Gross Salary',
                'tax' => 'Tax',
                'net_salary' => 'Net Salary',
                'to' => 'To',
                'apply_date' => 'Apply date',
                'pending' => 'Pending',
                'approved' => 'Approved',
                'cancelled' => 'Cancelled',
                'leave_from' => 'Leave From',
                'leave_to' => 'Leave to',
                'reason' => 'Reason',
                'leave' => 'Leave',
                'type_name' => 'Type Name',
                'total_days' => 'Total Days',
                'leave_type_list' => 'Leave Type List',
                'departments' => 'Departments',
                'department_name' => 'Department Name',
                'designations' => 'Designations',
                'staffs_payroll'=>'Staffs Payroll',
                'staff_no'=>'Staff No',
                'date_of_joining'=>'Date of Joining',
                'value'=>'Value',
                'payroll_summary'=>'Payroll Summary',
                'calculate'=>'calculate',
                'earning'=>'Earning',
                'deduction'=>'Deduction',
                'submit'=>'Submit',
                'edit_staff'=>'Edit Staff',
                'basic_info'=>'Basic Info',
                'staff_number'=>'Staff Number',
                'emergency_mobile'=>'Emergency Mobile',
                'current_address'=>'Current Address',
                'permanent_address'=>'Permanent Address',
                'qualifications'=>'Qualifications',
                'experience'=>'Experience',
                'payroll_details'=>'Payroll Details',
                'epf_no'=>'EPF NO',
                'bank_info_details'=>'Bank Info Details',
                'bank_account_name'=>'Bank Account Name',
                'branch_name'=>'Branch Name',
                'social_links_details'=>'Social Links Details',
                'facebook_url'=>'Facebook Url',
                'twitter_url'=>'Twitter Url',
                'linkedin_url'=>'Linkedin Url',
                'instragram_url'=>'Instragram Url',
                'update_staff'=>'Update Staff'
            ],
            //end human resource

            //additional for leave application
              [
                'leave' => 'Leave',
                'leave_define' => 'Leave Define',
                'my_remaining_leaves' => 'My Remaining Leaves',
                'remaining_days' => 'Remaining Days',
                'extra_taken' => 'Extra Taken',
                'total_days' => 'Total Days',
                'days' => 'Days'
              ],

            // end leave application


            //start examination
            [
                'examination' => 'Examination',
                'exam' => 'Exam',
                'add_exam_type' => 'Add Exam Type',
                'exam_schedule' => 'Exam Schedule',
                'marks_register' => 'Marks Register',
                'seat_plan' => 'Seat Plan',
                'exam_attendance' => 'Exam Attendance',
                'marks_grade' => 'Marks Grade',
                'send_marks_by_sms' => 'Send Marks By Sms',
                'question_group' => 'Question Group',
                'question_bank' => 'Question Bank',
                'online_exam' => 'Online Exam',
                'exam_type' => 'Exam Type',
                'exam_setup' => 'Exam Setup',
                'exam_name' => 'Exam Name',
                'sl' => 'Sl',
                'select_subjects' => 'Select Subjects',
                'exam_mark' => 'Exam Mark',
                'add_mark_distributions' => 'Add Mark Distributions',
                'exam_title' => 'Exam Title',
                'ct_AT_Exam' => 'Name',
                'mark_distribution' => 'Mark Distribution',
                'subject' => 'Subject',
                'total_mark' => 'Total Mark',
                'view_status' => 'View Status',
                'copy' => 'Copy',
                'add_exam_schedule' => 'add Exam Schedule',
                'exam_list' => 'Exam List',
                'marks' => 'Marks',
                'select_exam' => 'Select Exam',
                'percent' => 'Percent',
                'seat_plan_report' => 'Seat Plan Report',
                'assign_students' => 'Assign Students',
                'start_end_time' => 'start-end time',
                'total_students' => 'Total Students',
                'attendance_create' => 'Attendance Create',
                'grade' => 'Grade',
                'gpa' => 'GPA',
                'percent_from' => 'Percent From',
                'percent_upto' => 'Percent Upto',
                'send_marks_via_SMS' => 'Send Marks Via SMS',
                'select_receiver' => 'Select Receiver',
                'students' => 'Students',
                'select_group' => 'Select Group',
                'question_type' => 'Question Type',
                'multiple_choice' => 'Multiple Choice',
                'true_false' => 'True False',
                'fill_in_the_blanks' => 'Fill in the Blanks',
                'question' => 'Question',
                'number_of_options' => 'Number Of Options',
                'create' => 'Create',
                'option' => 'option',
                'true' => 'True',
                'false' => 'False',
                'suitable_words' => 'Suitable Words',
                'start_time' => 'Start Time',
                'end_time' => 'End time',
                'minimum_percentage' => 'Minimum Percentage',
                'instruction' => 'Instruction',
                'exam_date' => 'Exam Date',
                'time' => 'Time',
                'published' => 'Published',
                'manage_question' => 'Manage Question',
                'published_now' => 'Published Now ',
                'view_result' => 'View Result',
                'monday' => 'Monday',
                'tuesday' => 'Tuesday',
                'wednesday' => 'Wednesday',
                'thursday' => 'Thursday',
                'friday' => 'Friday',
                'Saturday' => 'Saturday',
                'sunday' => 'Sunday',
                'room_number' => 'Room Number',
                'not_scheduled' => 'Not Scheduled',
                'result_view'=>'Result View',
                'total_marks'=>'Total Marks',
                'obtained_marks'=>'Obtained Marks',
                'marking'=>'Marking',
                'view_answer_marking'=>'View answer & marking',
                'online_exam_question'=>'Online Exam Question',
                'question_list'=>'Question List',
                'questions'=>'Questions',
                'exam_details'=>'Exam Details',
                'passing_percentage'=>'Passing Percentage',
                'online_active_exams'=>'Online Active Exams',
                'take_exam'=>'Take Exam',
                'classes'=>'Classes',
                'exam_terms'=>'Exam Terms',
                'documents'=>'documents',
                'timeline'=>'Timeline',
                'Parent_Guardian_Details'=>'Parent / Guardian Details',
                'full_marks'=>'Full Marks',
                'results'=>'Results',
                'visible_to_this_person'=>'Visible to this person',
                ''=>'',
                ''=>'',
                ''=>'',
                ''=>'',
            ],
            //end examination

            // start academics
            [
                'academics' => 'Academics',
                'class_routine' => 'Class Routine',
                'class_routine_create' => 'Class Routine Create',
                'view_teacher_routine' => 'View Class Routine(Teacher)',
                'assign_subject' => 'Assign Subject',
                'assign_subject_create' => 'Assign Subject create',
                'assign_class_teacher' => 'Assign Class Teacher',
                'subjects' => 'Subjects',
                'class' => 'Class',
                'section' => 'Sections',
                'class_room' => 'Class Room',
                'n_a' => 'N/A',
                'class_teacher' => 'Class Teacher',
                'assign_teacher' => 'Assign teacher',
                'subject_name' => 'Subject Name',
                'theory' => 'Theory',
                'practical' => 'Practical',
                'subject_code' => 'Subject Code',
                'subject_type' => 'Subject Type',
                'capacity' => 'Capacity',
                'cl_ex_time_setup' => 'Cl/Ex Time Setup',
                'class_exam_time_setup' => 'Class & Exam Time Setup',
                'class_time' => 'Class Time',
                'time_type' => 'Time Type',
                'exam_time' => 'Exam Time',
                'period' => 'Period',
                'select_time' => 'Select Time',
                'not_assigned_yet' => 'Not assigned yet'
            ],
            // end academics

            // start HomeWork
            [
                'home_work' => 'HomeWork',
                'add_homework' => 'Add Homework',
                'homework_list' => 'Homework List',
                'evaluation_report' => 'Homework Evaluation Report',
                'submission' => 'Submission',
                'attach_file' => 'Attach File',
                'evaluation' => 'Evaluation',
                'created_by' => 'Created By',
                'complete' => 'Complete',
                'incomplete' => 'Incomplete'
            ],
            // end HomeWork

            // start communicate
            [
                'communicate' => 'Communicate',
                'notice_board' => 'Notice Board',
                'send_message' => 'Send Message',
                'send_email' => 'Send Email / Sms',
                'email_sms_log' => 'Email / Sms Log',
                'event' => 'Event',
                'notices' => 'Notices',
                'notice' => 'Notice',
                'publish' => 'Publish',
                'add_notice' => 'Add Notice',
                'add_a_notice' => 'Add a Notice',
                'publish_on' => 'Publish On',
                'Send_Email_Sms' => 'Send Email',
                'sms' => 'Sms',
                'individual' => 'Individual',
                'select_all' => 'Select All',
                'For_Sending_Email' => 'For Sending Email / Sms, It may take some seconds. So please take patience.',
                'send' => 'Send',
                'start_date' => 'Start Date',
                'to_date' => 'To Date',
                'from_date' => 'from Date',
                'details' => 'Details',
                'notice_date'=>'Notice Date',
                'update_content'=>'Update content'
            ],
            // end communicate

            //Start Library
            [
                'library' => 'Library',
                'add_book' => 'Add Book',
                'book_list' => 'Book List',
                'book_category' => 'Book Categories',
                'library_member' => 'Add Member',
                'member_list' => 'Issue/Return Book',
                'all_issued_book' => 'All Issued Book',
                'edit_book' => 'Edit Book',
                'book' => 'Book',
                'book_title' => 'Book Title',
                'select_book_category' => 'Select Book Category',
                'isbn' => 'ISBN',
                'publisher' => 'Publisher',
                'author_name' => 'Author Name',
                'rack' => 'Rack',
                'quantity' => 'Quantity',
                'book_price' => 'Book Price',
                'price' => 'Price',
                'category_name' => 'Category Name',
                'add_member' => 'Add Member',
                'member' => 'Member',
                'member_type' => 'Member Type',
                'select_student' => 'Select Student',
                'issue_books' => 'Issue Books',
                'full_name' => 'Full Name',
                'issue_return_Book' => 'Issue / Return Book',
                'issued_Book_List' => 'Issued Book List',
                'select_Book_Name' => 'Select Book Name',
                'search_By_Book_ID' => 'Search By Book ID',
                'author' => 'Author',
                'library_book_issue' => 'Library Book Issue',
                'staff_name' => 'Staff Name',
                'select_book' => 'Select Book',
                'issue_book' => 'Issue Book',
                'issued_book' => 'Issued Book',
                'book_number' => 'Book Number',
                'status' => 'Status',
                'issue_date' => 'Issue Date',
                'return_this_book'=>'Are you sure to Return This Book ?',
                'return_date' => 'Return Date'
            ],
            //end Library

            //start Inventory
            [
                'inventory' => 'Inventory',
                'item_category' => 'Item Category',
                'item_list' => 'Item List',
                'item_store' => 'Item Store',
                'supplier' => 'Supplier',
                'item_receive' => 'Item Receive',
                'item_receive_list' => 'Item Receive List',
                'item_sell' => 'Item Sell',
                'item_issue' => 'Item Issue',
                'select_item_category ' => 'Select Item Category ',
                'selected' => 'Selected',
                'total_in_stock' => 'Total in Stock',
                'store_name' => 'Store Name',
                'store_number' => 'Store Number',
                'company' => 'Company',
                'contact_person_name' => 'Contact Person Name',
                'contact_person' => 'Contact Person',
                'receive_details' => 'Receive Details',
                'select_supplier' => 'Select Supplier',
                'receive_date' => 'Receive Date',
                'product_name' => 'Product Name',
                'unit_price' => 'Unit Price',
                'sub_total' => 'Sub Total',
                'full_paid' => 'Full Paid',
                'total_paid' => 'Total Paid',
                'total_due' => 'Total Due',
                'receive' => 'Receive',
                'new' => 'New',
                'total_quantity' => 'Total Quantity',
                'partial_paid' => 'Partial Paid',
                'unpaid' => 'Unpaid',
                'refund' => 'Refund',
                'buyer' => 'Buyer',
                'issue_item' => 'Issue Item',
                'issue_a_item' => 'Issue a Item',
                'user_type' => 'User Type',
                'select_student_for_issue' => 'Select Student For Issue',
                'issue_to' => 'Issue To',
                'issued_item_list' => 'Issued Item List',
                'issued' => 'Issued',
                'returned' => 'Returned',
                'cancel_the_record' => 'You are about to cancel the record. This cannot be undone. are you sure?',
                'return' => 'Return',
                'purchase_details' => 'Purchase Details'
            ],
            //end Inventory

            //start transport
            [
                'transport' => 'Transport',
                'routes' => 'Routes',
                'vehicle' => 'Vehicle',
                'assign_vehicle' => 'Assign Vehicle',
                'student_transport_report' => 'Student Transport Report',
                'transport_route' => 'Transport Route',
                'route' => 'Route',
                'route_title' => 'Route Title',
                'fare' => 'Fare',
                'model' => 'Model',
                'year_made' => 'Year Made',
                'select_driver' => 'Select Driver',
                'license' => 'License',
                'select_route' => 'Select Route',
                'select_vehicle' => 'Select Vehicle',
                'father_phone' => 'Father\'s Phone',
                'mother_name' => 'Mother\'s Name',
                'mother_phone' => 'Mother\'s Phone'
            ],
            //end transport

            // start dormitory-15
            [
                'dormitory' => 'Dormitory',
                'dormitory_rooms' => 'Dormitory Rooms',
                'room_type' => 'Room Type',
                'student_dormitory_report' => 'Student Dormitory Report',
                'number_of_bed' => 'Number Of Bed',
                'cost_per_bed' => 'Cost Per Bed',
                'no_of_bed' => 'NO. OF BED',
                'dormitory_list' => 'Dormitory List',
                'boys' => 'Boys',
                'girls' => 'Girls',
                'intake' => 'Intake',
                'select_dormitory' => 'Select Dormitory',
                'guardian_phone' => 'Guardian\'s Phone'],
            // end dormitory

            // start reports
            [ 
                'reports' => 'Reports',
                'student_report' => 'Student Report',
                'guardian_report' => 'Guardian Reports',
                'student_history' => 'Student History',
                'student_login_report' => 'Student Login Report',
                'fees_statement' => 'Fees Statement',
                'balance_fees_report' => 'Balance Fees Report',
                'transaction_report' => 'Transaction Report',
                'class_report' => 'Class Report',
                'merit_list_report' => 'Merit List Report',
                'online_exam_report' => 'Online Exam Report',
                'mark_sheet_report' => 'Mark Sheet Report',
                'tabulation_sheet_report' => 'Tabulation Sheet Report',
                'student_fine_report' => 'Student Fine Report',
                'user_log' => 'User Log',
                'exam_routine' => 'Exam Routine',
                'select_type' => 'Select Type',
                'select_gender' => 'Select Gender',
                'nid' => 'NID',
                'Birth_Certificate_Number' => 'Birth Certificate Number',
                'select_admission_year' => 'Select admission Year',
                'start_end' => 'Start-End',
                'student_login_info' => 'Student Login Info',
                'login_info_report' => 'Login Info Report',
                'username' => 'Username',
                'password' => 'Password',
                'parent' => 'Parent',
                'reset' => 'Reset',
                'due_date'=>'Due Date',
                'partial'=>'Partial',
                'discount_of'=>'Discount of',
                'fees_report'=>'Fees Report',
                'paid_fees'=>'Paid Fees',
                'fees_collection_details'=>'Fees Collection Details',
                'number_of_student'=>'Number Of Student',
                'total_subjects_assigned'=>'Total Subjects assigned',
                'collection'=>'Collection',
                'due'=>'Due',
                'fees_details'=>'Fees Details',
                'class_routine_report'=>'Class Routine Report',
                'report'=>'Report',
                'teacher_class_routine_report'=>'Teacher Class Routine Report',
                'select_teacher'=>'Select Teacher',
                'school_management_system'=>'School Management System',
                'united_states_of_america'=>'House 25, Road 27, Block B, 54th Floor, New York, United States of America',
                'order_of_merit_list'=>'Order of merit list',
                'position'=>'Position',
                'average'=>'Average',
                'obtained_marks'=>'Obtained Marks',
                'top_obtained_mark'=>'Top Obtained Mark',
                'student_terminal_report'=>'Student Terminal Report',
                'progress_card_report'=>'Progress card report',
                'position_in_class'=>'Position in Class',
                'class_test'=>'Class Test',
                'remarks'=>'Remarks',
                'user'=>'User',
                'ip'=>'IP',
                'login_time'=>'Login Time',
                'user_agent'=>'User Agent'
            ], 
            // end reports


            //start system settings
            [
                'system_settings' => 'System Settings',
                'general_settings' => 'General Settings',
                'email_settings' => 'Email Settings',
                'payment_method_settings' => 'Payment Method Settings',
                'role' => 'Role',
                'base_group' => 'Base Group',
                'base_setup' => 'Base Setup',
                'academic_year' => 'Academic Year',
                'session' => 'Session',
                'holiday' => 'Holiday',
                'sms_settings' => 'Sms Settings',
                'language_settings' => 'Language Settings',
                'backup_settings' => 'Backup',
                'select_language' => 'Select Language',
                'native' => 'Native',
                'universal' => 'Universal',
                'make_default' => 'Make Default',
                'setup' => 'Setup',
                'change_logo' => 'Change Logo',
                'change_fav' => 'Change Favicon',
                'upload' => 'Upload',
                'school_name' => 'School Name',
                'school_code' => 'School Code',
                'language' => 'Language',
                'date_format' => 'Date Format',
                'currency' => 'Currency',
                'symbol' => 'Symbol',
                'sand' => 'Sand',
                'smtp' => 'SMTP',
                'from_name' => 'From Name',
                'from_email' => 'From Email',
                'server' => 'Server',
                'port' => 'Port',
                'security' => 'Security',
                'select_a_payment_gateway' => 'Select a Payment Gateway',
                'checked' => 'Checked',
                'paypal' => 'Paypal',
                'stripe' => 'Stripe',
                'payUMoney' => 'PayUMoney',
                'signature' => 'Signature',
                'client_id' => 'Client ID',
                'secret_id' => 'Secret ID',
                'stripe_api_secret_key' => 'Stripe API Secret Key',
                'stripe_publisher_key' => 'Stripe Publishable Key',
                'pay_u_money_key' => 'PayU Money Key',
                'pay_u_money_salt' => 'PayU Money Salt',
                'role_permission' => 'Role Permission',
                'assign_permission' => 'Assign Permission',
                'label' => 'Label',
                'base' => 'Base',
                'year_title' => 'Year Title',
                'starting_date' => 'Starting Date',
                'ending_date' => 'Ending Date',
                'select_a_SMS_service' => 'Select a SMS Service',
                'clickatell' => 'Clickatell',
                'settings' => 'Settings',
                'twilio' => 'Twilio',
                'api' => 'API',
                'sid' => 'SID',
                'authentication' => 'Authentication',
                'token' => 'Token',
                'registered_phone_number' => 'Registered Phone Number',
                'authentication_key_SID' => 'Authentication Key SID',
                'sender' => 'Sender',
                'country_code' => 'Country Code',
                'select_serial' => 'Select serial',
                'day_list' => 'Day list',
                'serial' => 'Serial',
                'upload_from_local_directory' => 'Upload From Local Directory',
                'file' => 'File',
                'cron_secret_key' => 'Cron Secret Key',
                'generate_key' => 'Generate key',
                'database_backup_list' => 'Database Backup List',
                'backup' => 'Backup',
                'created_date_time' => 'Created Date Time',
                'backup_files' => 'Backup Files',
                'weekend' => 'Weekend',
                'restore' => 'Restore',
                'default'=>'Default',
                'module'=>'Module',
                'module_link'=>'Module Link',
                'permission'=>'Permission',
                'site_title'=>'Site Title',
                'select_session'=>'Select Session',
                'select_date_format'=>'Select Date Format',
                'select_currency'=>'Select Currency',
                'currency_symbol'=>'Currency Symbol',
                'school_address'=>'School Address',
                'update_language'=>'Update Language',
                'language_setup'=>'Language Setup',

            ],
            //end front end settings
            [
                'front_end_settings'=>'Front End Settings',
                'add_news'=>'Add News',
                'news'=>'News',
                'news_list'=>'News List',
                'image'=>'Image',
                'publication_date'=>'Publication Date',
                'add_testimonial'=>'Add Testimonial',
                'testimonial'=>'Testimonial',
                'institution_name'=>'Institution Name',
                'location'=>'Location',
                'front_settings'=>'Front Settings'
            ],
            //common for all
            [
                'my_profile' => 'My Profile',
                'fees' => 'Fees',
                'pay_fees' => 'Pay Fees',
                'download_center' => 'Download Center',
                'student_study_material' => 'Study Materials',
                'examinations' => 'Examinations',
                'result' => 'result',
                'active_exams' => 'Active Exams',
                'book_issue' => 'Book issued',
                'my_children' => 'My Children',
                'exam_result' => 'Exam Result',
                'teacher_list' => 'Teacher list',
                'inserted_message' => 'Inserted Successfully',
                'updated_message' => 'Updated Successfully',
                'deleted_message' => 'Deleted Successfully',
                'inactive_message' => 'Inactivated Successfully',
                'active_message' => 'Activated Successfully',
                'backup_message' => 'Backup Successfully',
                'restore_message' => 'Restore Successfully',
                'not_found_message' => 'Ops! Data not Found',
                'error_message' => 'Ops! Something went wrong, please try again',
                'front_cms' => 'Front cms',
                'update_system' => 'Update System',
                'System_Status' => 'System Status',

                'Upgrade' => 'Upgrade',
                'Version' => 'Version',
                'Existing' => 'Existing',
                'Available' => 'Available', 
                'Alert' => 'Alert',
                'New_Features' => 'New Features',
                'copyright_text' => 'Copyright Text',
            ],
            [
                'point1'=>'Your CSV data should be in the format download file. The first line of your CSV file should be the column headers as in the table example. Also make sure that your file is UTF-8 to avoid unnecessary encoding problems.',
                'point2'=>'If the column you are trying to import is date make sure that is formatted in format Y-m-d (2018-06-06).',
                'point3'=>'Duplicate "Roll Number" (unique in section) rows will not be imported. Roll No used or not you can get from student report page search on class & section',
                'point4'=>'Duplicate "Guardian email & Guardian Phone" rows will not be imported. Guardian email & Guardian Phone used or not you can get from student report page search on class & section',
                'point5'=>'For student "Session" use ID',
                'point6'=>'For student "Gender" use ID',
                'point7'=>'For student "Blood Group" use ID',
                'point8'=>'For student "Religion" use ID',
                'point9'=>'For student "Guardian Relation" use capital O for Other, F for Father M for Mother.',
                'save_bulk_students'=>'save bulk students',
                'bank_account_number'=>'Bank Account Number',
                'IFSC_Code'=>'IFSC Code',
                'payment_ID'=>'Payment ID',
                'passing_marks'=>'Passing Marks',
                'website'=>'Website',
                'you_have'=>'You have',
                'new'=>'new',
                'notification'=>'notification',
                'mark_all_as_read'=>'Mark All As Read',
                'view_profile'=>'view profile',
                'completed'=>'Completed',
                'to_do_title'=>'To Do Title',
                'Designation_of_Signature_person'=>'Designation of Signature person',
                'student_wise'=>'Student Wise',
                'print'=>'print',
                'discount_of'=>'Discount of',
                'applied'=>'Applied',
                'fees_assign'=>'Fees Assign',

            ]

        ];
        $moduleIndex = 0;
        foreach ($translation_strings as $singleData) { //10
            foreach ($singleData as $key => $value) {
                $store = new SmLanguagePhrase();
                $store->modules = $moduleIndex;
                $store->default_phrases = $key;
                $store->en = $value;
               $store->save();
            }
            $moduleIndex++;
        }



    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('sm_language_phrases');
    }
}
